name: store_app
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  mobx:
  flutter_mobx:
  get_it: ^7.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  mobx_codegen:
  build_runner:

  flutter_lints: ^1.0.0

flutter:


  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  fonts:
    - family: Vectory
      fonts:
      - asset: assets/fonts/Vectory-Medium.ttf
      
    - family: Rocko
      fonts:
      - asset: assets/fonts/Rocko.ttf

    - family: RockoUltra
      fonts:
      - asset: assets/fonts/RockoUltra.ttf    

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700